### ISSUE TITLE
Unable to successfully install.

### ISSUE THREAD

**Issue by iamraffe** [fatiherikli/react-designer#11]
Hi there,

Been trying for a while now to install this package without success and quite frankly never had this happened before so I'm at a loss.

`npm install react-designer`or by placing it within my package.json and then hitting `npm install` don't work.

Is there any more configuration that needs to happen that I'm missing?

**Comment by raffe90** [comment]
After some digging I have found a way for the package to work.

After installing I had to go into my node_modules/react-designer folder and run
` npm install `
and then
 `npm run clean && npm run build`

Also had to update my webpack.config.js file and add:

```
  resolve: {
    alias: {
      'react': path.join(__dirname, 'node_modules', 'react')
    },
  },
```
because I was getting an error saying there were duplicate React instances.

**Comment by raffe90** [comment]
The issue is related with this: https://phabricator.babeljs.io/T2041

The problem is the Babel CLI commands inside NPM scripts fails silently (in our case  "babel -d lib/ src/"), so there was no error being displayed. Adding "babel-cli" package back to dependencies seems to have fixed that, so great.

**Comment by jkarttunen** [comment]
Which Node and NPM versions are you using? Can't reproduce this.
